# Generated by Django 2.2 on 2019-06-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20190610_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='superuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
