# Generated by Django 2.2 on 2019-06-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_auto_20190610_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_egresado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_egresado',
            field=models.BooleanField(default=False),
        ),
    ]
