# Generated by Django 2.2 on 2019-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_auto_20190610_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superuser',
            name='is_superusuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superusuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
