# Generated by Django 2.2 on 2019-06-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_auto_20190611_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contraseña',
        ),
    ]
