# Generated by Django 2.2 on 2019-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_auto_20190611_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_administrador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_egresado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superusuario',
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_administrador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_egresado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_superusuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='egresado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='egresado',
            name='is_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='egresado',
            name='is_egresado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='egresado',
            name='is_superusuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
