# Generated by Django 2.2 on 2019-06-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_auto_20190611_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Password'),
        ),
    ]
