# Generated by Django 2.2 on 2019-06-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0013_auto_20190612_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.Paises'),
        ),
    ]
