# Generated by Django 2.2 on 2019-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0002_auto_20190602_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrarse',
            options={'verbose_name': 'Egresado', 'verbose_name_plural': 'Egresados'},
        ),
    ]
