# Generated by Django 2.2 on 2019-06-19 03:07

import app_registrarse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0002_auto_20190616_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__nombres']},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_registrarse.models.custom_upload_to),
        ),
    ]
