# Generated by Django 2.2 on 2019-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0003_auto_20190602_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarse',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='registrarse',
            name='apellidos',
            field=models.CharField(default='', max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='registrarse',
            name='pais',
            field=models.CharField(default='', max_length=30, verbose_name='Pais'),
        ),
    ]
