# Generated by Django 2.2 on 2019-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0004_auto_20190602_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarse',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='registrarse',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
