# Generated by Django 2.2 on 2019-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0005_auto_20190602_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarse',
            name='activacion',
            field=models.BooleanField(default=False, verbose_name='activacion'),
        ),
        migrations.AddField(
            model_name='registrarse',
            name='contraseña',
            field=models.CharField(default='', max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='registrarse',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Genero'),
        ),
    ]
